<a href="https://colab.research.google.com/github/MukherjeeSangita/ml_project/blob/master/WebScrapping_python_events.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Web Scrapping using Beautifulsoup

In [1]:
import requests 
import pandas as pd
from bs4 import BeautifulSoup
from collections import defaultdict

url='https://www.python.org/events/python-events'
res=requests.get(url)
soup=BeautifulSoup(res.text, 'html.parser')
events= soup.find('ul',{'class':'list-recent-events'}).findAll('li')
details= defaultdict(list)
for event in events:
    title=event.h3.text
    location=event.find('span',{'class':'event-location'}).text
    time=event.find("time").text
    details['title'].append(title)
    details['location'].append(location)
    details['time']=time
pd.DataFrame(details)

,title,location,time
0,PyCon APAC 2022,"Online, Taiwan",21 Sept. – 25 Sept. 2022
1,PyCon SK 2022,"Bratislava, Slovakia",21 Sept. – 25 Sept. 2022
2,PyBay 2022,"San Francsisco, USA and Online",21 Sept. – 25 Sept. 2022
3,PyHEP 2022,Online,21 Sept. – 25 Sept. 2022
4,PyCon UK 2022,"Cardiff City Hall, UK",21 Sept. – 25 Sept. 2022
5,DjangoCon Europe 2022,"Porto, Portugal",21 Sept. – 25 Sept. 2022